### ISSUE TITLE
Crossbrowser - Austria flag not rendering properly in IE

### ISSUE THREAD

**Issue by Otto-AA** [FCCVienna/FCCVienna.github.io#11]
Using: 
IE
Version: 11.0.9600.18762
Updateversions: 11.0.45 (KB4034733)

It showed the flag without the white stripe, even though the direct link to the .svg rendered properly:
![getfileattachment](https://user-images.githubusercontent.com/21040751/29636266-4919040a-8850-11e7-9ac0-8821fb397b61.png)

Possible solutions I found:

- Using a picture instead of SVG
- It seems like here someone encountered the same problem, probably someone can look if it works in IE (I currently can't work with IE) https://stackoverflow.com/questions/18471711/svg-not-rendering-in-ie

**Comment by Createdd** [comment]
Thanks! Will have a look!

**Comment by Createdd** [comment]
pending PR #19

**Comment by robaxelsen** [comment]
Solved as part of PR #19.
