### ISSUE TITLE
Shadow of navbar-icons is too big

### ISSUE THREAD

**Issue by Otto-AA** [FCCVienna/FCCVienna.github.io#13]
(Not a big issue, I know, but it kinda distracts me O.o)

When hovering an icon in the navbar (big screen needed for their visibility), its background gets darker. But the area which gets darker is too tall, so a small part is also in front of the background. Here is a close up of it:
![grafik](https://user-images.githubusercontent.com/21040751/29680727-cb84513c-8905-11e7-928d-76d8df077cb9.png)

A way to fix this is, to add the class .material-icons instead of .small (e.g. `<li><a href="https://www.meetup.com/de-DE/Free-Code-Camp-Vienna/"><i class="fa fa-meetup material-icons" aria-hidden="true"></i></a></li>`). 
But this also leads to a smaller icon, so I am not sure if this is worth it.

(using firefox 54.0.1)

**Comment by robaxelsen** [comment]
Hi @Otto-AA :) Well spotted.

To be honest, this initially looked nice as it so me, but having had a closer look I am not sure anymore. Would you be willing to push a PR for this if you can come up with a fix, so we can visually compare?
