### ISSUE TITLE
Navbar icons and .hover-card changes are undone

### ISSUE THREAD

**Issue by Otto-AA** [FCCVienna/FCCVienna.github.io#16]
I don't know in how far this is intented, but I just recognised that some pull-requests I made are reverted.
Those are:
- #15 | Update navbar icons in index.html
- #12 | Add alt-text for images in index.html
- #9   | card-hover tooltips

Maybe this is due to the merge of the sponsors branche, but as I am new to github I am not sure.

**Comment by Createdd** [comment]
@Otto-AA  Yes it is :) We are working on it :) Don't worry

**Comment by Createdd** [comment]
@Otto-AA  Now it should be working and be up-to-date :)  Or have I missed something?

**Comment by Otto-AA** [comment]
@DDCreationStudios Yeah, my changes are all there again :)
