### ISSUE TITLE
Insecure images are blocked in Chrome

### ISSUE THREAD

**Issue by Createdd** [FCCVienna/FCCVienna.github.io#20]
Err: Mixed Content: The page at 'https://fccvienna.github.io/' was loaded over HTTPS, but requested an insecure image 'http://www.sektor5.at/wp-content/themes/sektor5.at/images/sektor5_logo@2x.png'. This content should also be served over HTTPS.

Maybe reference other source?

![image](https://user-images.githubusercontent.com/22077628/29740734-8cd1da1e-8a5d-11e7-8157-68d48ade7b4b.png)

**Comment by Otto-AA** [comment]
I found an article explaining it pretty good: https://developers.google.com/web/fundamentals/security/prevent-mixed-content/what-is-mixed-content

Basically the http resource would make the page more insecure, so it blocks the request.

The easiest solution I can think of, is to save the file at the github-repository (which is https) and link to that one.
