### ISSUE TITLE
Background color issues

### ISSUE THREAD

**Issue by robaxelsen** [FCCVienna/FCCVienna.github.io#30]
I just discovered that we have some issues with background color for appearing different for different sections of the page.

See screenshot:
![screencapture-file-home-raxelsen-code-fccvienna-github-io-index-html-1504859222369-smaller](https://user-images.githubusercontent.com/13132899/30203326-15a6ad96-9482-11e7-8e34-9a4240f0008e.jpg)

I am using Google Chrome Version 61.0.3163.79 on Ubuntu 16.04.

**Comment by Createdd** [comment]
the sections should have a different color! To identify them as a different section. I agree that we can also brainstorm a better, more appealing solution, though ;) 

other feedback is very welcome!

**Comment by robaxelsen** [comment]
@DDCreationStudios maybe you misunderstood my issue, or I am misunderstanding you :) To clarify, I have no real objection with the current colors, but I am reporting on the issue that each section has two separate background colors - one overall for the section, and another color wrapped closer around the content itself.

Another more "zoomed in" screenshot to further illustrate:
![screenshot from 2017-09-08 15-14-15](https://user-images.githubusercontent.com/13132899/30213254-9086eeba-94a8-11e7-9cfc-6e964b306eaf.png)

See it now?

**Comment by Createdd** [comment]
ahh I see what you mean. I think it's because we nested teal classes on the divs :) 
good catch

**Comment by Otto-AA** [comment]
Colors are fine on Firefox 55.0.3 :)
![grafik](https://user-images.githubusercontent.com/21040751/30272955-35141692-96f7-11e7-8903-239b800c6471.png)

**Comment by robaxelsen** [comment]
I am not able to find a way to solve this. I've tried inspecting the elements in Chrome Dev Tools without any helpful result, and trying to map the color to the materialize css did not help either. I propose we close this ticket, and reopen the issue later if other's also experience it. Agreed @DDCreationStudios?

**Comment by Createdd** [comment]
@robeerob Did you try to remove the nested teal classes?

**Comment by robaxelsen** [comment]
@DDCreationStudios You mean this part?:
`<div class="section teal darken-1"></div>`

Removing darken-1 does not make any difference. Still same dual-color issue.

**Comment by Createdd** [comment]
@robeerob I will have a look at it when I have time :)

**Comment by Createdd** [comment]
@robeerob  I tried it now with different screens. Seems to be dependent on the screen. With high quality resolution and even high zoom there is no difference in the colors and sections. 

I close this issue. 

Feel free to reopen if necessary or solutions can be provided.
