### ISSUE TITLE
Partner logos need fixed sizes

### ISSUE THREAD

**Issue by robaxelsen** [FCCVienna/FCCVienna.github.io#31]
After merging the last PR, the partner logos are "acting up". Need to have fixed size defined. I did not encounter this problem when testing the PR branch locally.

Screenshot:
![screenshot from 2017-09-08 14-54-41](https://user-images.githubusercontent.com/13132899/30212618-fe9e9c84-94a5-11e7-971c-853cb017f911.png)

@phbrasiliano can you please fix, if you have time?

**Comment by Createdd** [comment]
@robeerob  
![image](https://user-images.githubusercontent.com/22077628/30212775-b279cd14-94a6-11e7-9bcc-1ad06ec2e9fd.png) they look good in my browser

**Comment by Createdd** [comment]
@robeerob did you load the css files? because the links also appear differently

**Comment by robaxelsen** [comment]
Works for me now, thanks for reporting. Must have been a cache issue :) Closing this.
