### ISSUE TITLE
improve display of contributors

### ISSUE THREAD

**Issue by Createdd** [FCCVienna/FCCVienna.github.io#36]
- maybe add circular pictures to the names
- make sure that all names are linked to their profile/homepage
- sort alphabetical or according to contribute date

**Comment by himanshuc3** [comment]
I'd like to contribute mate!!

**Comment by robaxelsen** [comment]
@himanshuc3 Great, thanks. We will get links and pictures from the contributors. Could you please create a PR where you use a dummy picture and links, and then we can add the real ones once ready?

**Comment by Createdd** [comment]
@himanshuc3 Awesome! You are familiar with the workflow on Github? Just clone the repo, add your changes, push you branch and open a pull request.

In my opinion you can already use pictures from the Github repo and also add the links to their homepages/profiles if you want. :) 

If you have any questions feel free to ask :)

**Comment by robaxelsen** [comment]
@DDCreationStudios I went ahead and downloaded all pictures from the ones we have GiotHub profile links to. Would also like to add Monika Schrenk who's been having talks and helping out earlier. I also went ahead and contacted all the contributors with missing links, except for Manuel Matuzovic. Can you contact him?

@himanshuc3 I will add all the GitHub photos in a PR, and then you can use them once merged. Will tag you in the PR.

**Comment by robaxelsen** [comment]
**Link to add (will update when/if I get more links)**
Adi Marvillo: [https://github.com/darkhouse2](https://github.com/darkhouse2)
Achim Tecklenburg: [https://github.com/achim-tecklenburg](https://github.com/achim-tecklenburg) | [Picture (consent given)](https://www.dropbox.com/s/1u4x98pbsjfae9g/IMG_3146.JPG?dl=0)
Manfred Specht: [http://javascript.consulting/](http://javascript.consulting/)
Monika Schrenk: [https://github.com/random-access](https://github.com/random-access)

**Comment by robaxelsen** [comment]
@himanshuc3 We decided to not add GitHub photos after all, due to legal/copyright issues. Please use a direct link to the GitHub profile pictures instead.

**Comment by phbrasiliano** [comment]
Guys, I just found out that if you add .png at any given Github profile, you get a link to the users avatar. For example, my github profile link is [https://github.com/phbrasiliano](https://github.com/phbrasiliano), if you add .png for that you can easily use the avatar [https://github.com/phbrasiliano.png](https://github.com/phbrasiliano.png).
As they are all the same size, I guess using it them on the project would be easy.

**Comment by robaxelsen** [comment]
Awesome, @phbrasiliano! Well spotted. That will be helpful for this issue.

Hi @himanshuc3, are you still working on this? If not, please let us know so we can re-assign the issue.

**Comment by rettetdemdativ** [comment]
I'm also working on the issue right now so if that's ok, I could create a pull request in like half an hour max. I'm just not sure about whether contributors without a linked GitHub profile should have like a stock image instead of their GitHub one?

**Comment by rettetdemdativ** [comment]
![screenshot-2017-10-21 at 15 57 17](https://user-images.githubusercontent.com/5265630/31852475-882d8c0a-b678-11e7-9de7-d6d2ac05ea9b.png)
This is what I have right now. Any suggestions?

edit: I tried having the list items left-aligned so they're all in one line, but I don't think it looks good. Personally, I prefer the version in this screenshot.

**Comment by robaxelsen** [comment]
@calmandniceperson looks great! Maybe we can just use GitHub's default profile avatar for the missing ones.

[GitHub default profile avatar link](https://github-images.s3.amazonaws.com/enterprise/2.8/assets/images/help/profile/identicon.png)

**Comment by rettetdemdativ** [comment]
@robeerob Just added the default avatar to my pull request.

**Comment by robaxelsen** [comment]
Closing this due to work of @calmandniceperson and help from @phbrasiliano. @himanshuc3 please create a new issue if you want to suggest any improvements.
