### ISSUE TITLE
add the sponsor "101" in the partners and friends section

### ISSUE THREAD

**Issue by Createdd** [FCCVienna/FCCVienna.github.io#37]
![image](https://user-images.githubusercontent.com/22077628/30755034-583fd9d6-9fc5-11e7-9ddc-8b8b947d5c30.png)

**Comment by phbrasiliano** [comment]
Hey, can you send me the page for 101, so I can add it to the website

**Comment by robaxelsen** [comment]
@phbrasiliano http://101.at/

**Comment by robaxelsen** [comment]
Closing this.

@phbrasiliano For future reference, this would have closed automatically if you would have written "closes #37" without issue (not closes issue #37). But well done on the contribution and PR. Thanks A LOT for the work and effort :) :+1:
