### ISSUE TITLE
Should we adapt a gitflow workflow?

### ISSUE THREAD

**Issue by Createdd** [FCCVienna/FCCVienna.github.io#44]
Should we adapta Gitflow workflow here as well? 
For me it would make sense, since the site is getting bigger and as with the unintended merge in #43, we can establish a fallback for the main site.

I would then set up all instructions for contributing.

@robeerob

**Comment by robaxelsen** [comment]
@DDCreationStudios Sounds good to me! Thanks for the initiative, and for offering to set up instructions.

**Comment by Createdd** [comment]
closed due to https://github.com/DevelopersRising/DevelopersRising/issues/29
