### ISSUE TITLE
Improve the display of sponsors on mobile

### ISSUE THREAD

**Issue by phbrasiliano** [FCCVienna/FCCVienna.github.io#47]
That is just a small change, but I realized that the display of the sponsors logos on mobile could use some padding between them. I could change it myself, but I was not sure if it would be better to open an issue first (sorry guys, I'm still learning).

**Comment by robaxelsen** [comment]
@phbrasiliano Ah yes, well spotted. Thanks for reporting in an issue!

You can work on it, no problem :)
