### ISSUE TITLE
add a section displaying sponsors

### ISSUE THREAD

**Issue by Createdd** [FCCVienna/FCCVienna.github.io#5]
especially
- sektor5
- stockwerk
- kivu technologies

**Comment by Frazer** [comment]
I've done something basic. I hope its ok.

https://github.com/FCCVienna/FCCVienna.github.io/pull/10

Someone might want to change the background color on the sponsors sections - with the text, and with the images

**Comment by Createdd** [comment]
#10 #14  #17 #18 

done!

See https://github.com/FCCVienna/FCCVienna.github.io/network for explanation.

![image](https://user-images.githubusercontent.com/22077628/29740789-15a06aa8-8a5f-11e7-9fe0-f1199aad28ef.png)
