### ISSUE TITLE
Add contributors to list

### ISSUE THREAD

**Issue by robaxelsen** [FCCVienna/FCCVienna.github.io#57]
Add [these contributors](https://github.com/FCCVienna/FCCVienna.github.io/issues/36#issuecomment-334709076) to the contributors section on our website.

@calmandniceperson feel free to work on this one if you'd like, seeing that you've just pushed a related PR for this section.

**Comment by Hugainz** [comment]
@robeerob I'm available to do this, if you'd like :)

**Comment by rettetdemdativ** [comment]
I'll create a separate PR for this one if that's ok. Should just be a merge conflict at Adi's list entry if you merge both of my PRs.

**Comment by Createdd** [comment]
see PR #56
