### ISSUE TITLE
Using photos from October 2017 meetup

### ISSUE THREAD

**Issue by rettetdemdativ** [FCCVienna/FCCVienna.github.io#60]
Since we now have new photos from the last meetup of which most are really good and look very professional, I think we should use some of them on the homepage.

My personal suggestion would be to use some of the images below because they kind of show who we are and what we do, which allows people to get a bit of an impression before their first FCC meetup.

https://photos.app.goo.gl/h4xxTVUIfzYTov8W2
https://photos.app.goo.gl/bCw4uaBPHP3vRTPy2
https://photos.app.goo.gl/er1h6N9dRrcvL9hF3
https://photos.app.goo.gl/hLINMbirQmq5n6K62
https://photos.app.goo.gl/t4HDl76Ur7WD9vH53
https://secure.meetupstatic.com/photos/event/7/8/3/9/highres_465630777.jpeg
https://secure.meetupstatic.com/photos/event/7/2/7/e/600_465509310.jpeg

Maybe someone could implement a slideshow where the image of the group is right now:
<img width="1319" alt="screen shot 2017-10-26 at 2 16 27 pm" src="https://user-images.githubusercontent.com/5265630/32052367-4f594e3a-ba58-11e7-89d0-8591c4713a1e.png">

**Comment by Createdd** [comment]
@calmandniceperson Great idea! Feel free to add some and open a PR. :)

**Comment by rettetdemdativ** [comment]
@DDCreationStudios I'll try to make a slideshow with some of the images. What about permissions? I suppose we need to ask people for their permission...?

**Comment by robaxelsen** [comment]
@calmandniceperson Great idea! You can use all those photos, except for the last two ones hosted at meetup.com. Those we would need permissions to share yes. The rest should be fine.

**Comment by rettetdemdativ** [comment]
Great! I'll look into it tomorrow and create a pull request once it's ready 👍

**Comment by Createdd** [comment]
@calmandniceperson  Can I close this issue or are you still working on it ? :P

**Comment by rettetdemdativ** [comment]
@DDCreationStudios Sorry, I completely forgot about this. I started working on it, so I could try and finish it within the next couple of days :)
